server:
  port: 10000

eureka:
  instance:
    hostname: eurekaServer10000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eurekaServer10001:10001/eureka/
  server:
    enable-self-preservation: false