server:
  port: 17001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/hhhx009/configuration.git


eureka:
  client:
    service-url:
      defaultZone: http://eurekaServer10000:10000/eureka/,http://eurekaServer10001:10001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

