server:
  port: 18000

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      default-filters:
        - DefaultFallbackFilter

      routes:
        - id: userServer
          uri: lb://user-server
          predicates:
            - Path=/UserController/*/**
          filters:
            - UserFallbackFilter


        - id: foodServer
          uri: lb://food-server
          predicates:
            - Path=/FoodController/*/**


        - id: businessServer
          uri: lb://business-server
          predicates:
            - Path=/BusinessController/*/**
          filters:
            - name: CircuitBreaker
              args:
                name: businessCircuitBreaker
                fallbackUri: forward:/fallback/business

        - id: cartServer
          uri: lb://cart-server
          predicates:
            - Path=/CartController/*/**
          filters:
            - name: CircuitBreaker
              args:
                name: cartCircuitBreaker
                fallbackUri: forward:/fallback/cart

        - id: deliveryaddressServer
          uri: lb://deliveryaddress-server
          predicates:
            - Path=/DeliveryAddressController/*/**
          filters:
            - name: CircuitBreaker
              args:
                name: deliveryCircuitBreaker
                fallbackUri: forward:/fallback/delivery


        - id: ordersServer
          uri: lb://orders-server
          predicates:
            - Path=/OrdersController/*/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/order

resilience4j:
  circuitbreaker:
    instances:
      fallbackcmd:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5000
        failureRateThreshold: 50




eureka:
  client:
    service-url:
      defaultZone: http://eurekaServer10000:10000/eureka,http://eurekaServer10001:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
